"""Changing blog content column max characters from 10000 to 1000000

Revision ID: c75a7dcdcbb4
Revises: 
Create Date: 2025-07-13 20:33:12.266555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75a7dcdcbb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=100000),
               type_=sa.String(length=1000000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=100000),
               existing_nullable=False)

    # ### end Alembic commands ###
